const SHIVAN_VAZHIKATI_CATALOG = [
  {
    key: "kaveri-vada-karai",
    label: "Kaveri Vada Karai",
    shortLabel: "North of Kaveri",
    color: "#8d4a1d",
    summary: "Chola temples on the northern side of the Kaveri river system.",
    items: [
      "Kovil (Chidambaram)",
      "Tiruvetkalam",
      "Tirunelvayil",
      "Tirukkazhippalai",
      "Tirunallurpperumanam",
      "Mahendrapalli",
      "Ten Tirumullaivayil",
      "Kalikkaamoor",
      "Tiruchaaikaadu",
      "Pallavaneeswaram",
      "Thiruvenkadu",
      "Keezhai Tirukkattuppalli",
      "Thirukkurugavur",
      "Sirkazhi",
      "Tirukkolakka",
      "Pullirukkuvelur (Vaideeswaran Koyil)",
      "Kannaar Kovil",
      "Tirukkadaimudi",
      "Tiruninriyur",
      "Tiruppunkur",
      "Tiruneedur",
      "Anniyur",
      "Tiruvelvikudi",
      "Edirkolpaadi",
      "Tirumanancheri",
      "Tirukkurukkai",
      "Karuppariyalur",
      "Kurakkukka",
      "Tiruvaalkoliputrur",
      "Tirumannippadikkarai",
      "Omampuliyur",
      "Tirukkaanaattumulloor",
      "Tirunaarayur",
      "Kadambur",
      "Pandanallur",
      "Kanjanoor",
      "Tirukkodikka",
      "Tirumangalakkudi",
      "Tiruppanantaal",
      "Tiruvaappaadi",
      "Tirucheignalur",
      "Tirundudevankudi",
      "Tiruviyalur",
      "Kottaiyur",
      "Innambar",
      "Thirupirambiyam",
      "Vijayamangai",
      "Tiruvaikavur",
      "Vadakurangaaduturai",
      "Tiruppazhanam",
      "Thiruvaiyaru",
      "Tiruneittanam",
      "Tirupperumpuliyur",
      "Thirumazhapadi",
      "Tiruppazhuvur (Aalanturai)",
      "Tirukkaanoor",
      "Anbilalanturai",
      "Tirumaanturai",
      "Tiruppaatrurai",
      "Tiru Aanaikkaa",
      "Tiruppainneeli",
      "Tiruppaachilasramam",
      "Tiruveengoimalai"
    ]
  },
  {
    key: "kaveri-then-karai",
    label: "Kaveri Then Karai",
    shortLabel: "South of Kaveri",
    color: "#b76535",
    summary: "The largest cluster of Chola-region Paadal Petra Sthalams south of the Kaveri.",
    items: [
      "Vaatpokki",
      "Kadambar Kovil",
      "Thirupparaithurai",
      "Tirukkarkudi (Uyyakkondan Malai)",
      "Thirumukeeswaram",
      "Tiruchirappalli",
      "Tiruverumbur",
      "Nedunkalam",
      "Melaittirukkattuppalli",
      "Tiruvalampozhil",
      "Tiruppoonturutti",
      "Thirukkandiyur",
      "Tiruchotrutturai",
      "Tiruvedikudi",
      "Tenkudittittai",
      "Tirupullamangai",
      "Tiruchakrapalli",
      "Thirukkarugavur",
      "Tiruppaalaitturai (Papanasam)",
      "Tirunallur",
      "Aavoor Pasupateeswaram",
      "Satthi Mutram",
      "Patteswaram",
      "Pazhayarai",
      "Tiruvalanchuzhi",
      "Adi Kumbeswarar Temple",
      "Tirukkudandai Keezhkottam",
      "Kudandaikkaaronam",
      "Tirunageswaram",
      "Tiruvidaimarudur",
      "Ten Kurangaaduturai",
      "Tiruneelakkudi",
      "Tiruvaikalmaadakkovil",
      "Tirunallam",
      "Tirukkozhambam",
      "Tiruvavaduturai",
      "Tirutturutti",
      "Tiruvazhundur",
      "Mayiladuturai",
      "Viilanagar",
      "Tiruppariyalur",
      "Tiruchemponpalli",
      "Tirunanipalli",
      "Tiruvalampuram",
      "Tiruttalaichankadu",
      "Aakkoor",
      "Tirukkadavur",
      "Tirukkadavur Mayaanam",
      "Tiruvettakkudi",
      "Tiruttelicheri",
      "Dharumapuram",
      "Thirunallar",
      "Tirukkottaru",
      "Ambar",
      "Ambar Maakaalam",
      "Tirumeeyachur",
      "Tirumeeyachur Ilamkovil",
      "Thilataipati",
      "Tiruppaampuram",
      "Sirukudi",
      "Tiruveezhimizhalai",
      "Tiruvanniyur",
      "Karuvili Kottittai",
      "Penu Perunturai",
      "Naraiyur",
      "Arisirkaraiputtur",
      "Sivapuram",
      "Kalayanallur",
      "Tirukkarukkudi",
      "Tiruvanchiyam",
      "Nannilam",
      "Tirukkondeeswaram",
      "Tiruppanaiyur",
      "Virkudi",
      "Tiruppugalur",
      "Tiruppugalur Vardhamaneswaram",
      "Ramanadeeswaram",
      "Tiruppayatrankudi",
      "Tiruchenkattankudi",
      "Thirumarugal",
      "Tiruchaattamangai",
      "Nagaikkaronam",
      "Sikkal",
      "Keevalur",
      "Tiruttevur",
      "Palliyin Mukkoodal",
      "Achaleswaram",
      "Tiruvarur",
      "Arurparavaiumandali",
      "Vilamar",
      "Karaveeram",
      "Peruvelur",
      "Talaiyalankadu",
      "Tirukkudavaayil",
      "Tirucherai",
      "Tirunalurmayaanam",
      "Kaduvaaikaaraiputhur",
      "Tiruvirumpoolai",
      "Aradaipperumpazhi",
      "Avalivanallur",
      "Paridiniyamam",
      "Tiruvenniyur (Koyil Venni)",
      "Tiruppoovanur",
      "Paadaaleeswaram",
      "Tirukkalar",
      "Tiruchitremam",
      "Tiru Usaattaanam",
      "Tiruidumbavanam",
      "Kadikkulam",
      "Tandalaineeneri",
      "Kottur",
      "Vanduturai",
      "Tirukkollampudur",
      "Pereyil",
      "Tirukkollikkadu",
      "Tenkoor",
      "Tirunellikka",
      "Tirunatyattankudi",
      "Tirukkarayil",
      "Kanraappur",
      "Valivalam",
      "Kaichinam",
      "Tirukkolili",
      "Tiruvaimur",
      "Tirumaraikkadu",
      "Tiru Agathiyan Palli",
      "Kodikkarai",
      "Kiliyanur",
      "Tiruvidaivai"
    ]
  },
  {
    key: "tondai-nadu",
    label: "Tondai Nadu",
    shortLabel: "Tondai Nadu",
    color: "#35594f",
    summary: "Northern Tamil region temples centered around Kanchipuram, Chennai, and nearby sacred sites.",
    items: [
      "Kachi Ekambam",
      "Kachi Metrali",
      "Onakanthan Thali",
      "Kachi Anekatangavadam",
      "Kachi Nerikkaaraikkadu",
      "Kuranganilmuttam",
      "Tirumaagaral",
      "Tiruvothur",
      "Panankattur",
      "Tiruvallam",
      "Thirumarperu",
      "Tiruvooral, Takkolam",
      "Ilambayankottur",
      "Tiruvirkolam",
      "Thiruvalangadu",
      "Tiruppaasur",
      "Tiruvenpakkam",
      "Tirukkallil",
      "Sri Kalahasti",
      "Thiruvotriyur",
      "Tiruvalithayam",
      "Vada Tirumullaivayil",
      "Thiruverkadu",
      "Tirumayilai",
      "Thiruvanmiyur",
      "Tirukkachoor",
      "Tiruvidaichuram",
      "Tirukalukundram",
      "Tiru Acharapakkam",
      "Tiruvakkarai",
      "Arasili",
      "Irumbai Maakalam"
    ]
  },
  {
    key: "nadu-nadu",
    label: "Nadu Nadu",
    shortLabel: "Nadu Nadu",
    color: "#c8843c",
    summary: "Temples across the historic middle country between Chola and Tondai spheres.",
    items: [
      "Tirunelvayil Aratturai",
      "Pennaagadam",
      "Goodalaiyatrur",
      "Erukkattampuliyur",
      "Tiruttinai Nagar",
      "Tiruchopuram",
      "Tiruvatikai",
      "Thirunaavalur",
      "Tirumudukunram",
      "Tirunelvennei",
      "Tirukkovilur",
      "Arankandanallur",
      "Tiruvidaiyaru",
      "Thiruvennainallur",
      "Tirutturaiyur",
      "Vatukur",
      "Tirumaanikkuzhi",
      "Thirupathiripuliyur",
      "Tirumundeeswaram",
      "Puravaar Panankattur",
      "Tiruvamathur",
      "Tiruvannamalai"
    ]
  },
  {
    key: "pandya-nadu",
    label: "Pandya Nadu",
    shortLabel: "Pandya Nadu",
    color: "#ad5e43",
    summary: "Southern Tamil Shaiva temples tied to Madurai, Ramanathapuram, Tirunelveli, and surrounding regions.",
    items: [
      "Aalavaai (Madurai)",
      "Aappudaiyaar Kovil",
      "Tirupparankunram",
      "Tiruvedakam",
      "Tirukkodunkunram",
      "Tirupputhur",
      "Thiruppunavayil",
      "Rameswaram",
      "Tiruvadanai",
      "Tirukkaanapper",
      "Tiruppoovanam",
      "Thiruchuzhial",
      "Thirukutralam",
      "Tirunelveli"
    ]
  },
  {
    key: "kongu-nadu",
    label: "Kongu Nadu",
    shortLabel: "Kongu Nadu",
    color: "#7f8441",
    summary: "Western Tamil temples associated with Kongu country.",
    items: [
      "Avinaasi",
      "Thirumuruganpoondi",
      "Thirunana",
      "Kodimadachenkunoor",
      "Venchamaakoodal",
      "Paandikkodumudi",
      "Karuvoor Aanilai"
    ]
  },
  {
    key: "eezha-nadu",
    label: "Eezha Nadu",
    shortLabel: "Sri Lanka",
    color: "#6d6fa6",
    summary: "The Sri Lankan Paadal Petra Sthalam tradition.",
    items: ["Tirukkonamalai", "Tirukketheeswaram"]
  },
  {
    key: "malai-nadu",
    label: "Malai Nadu",
    shortLabel: "Kerala",
    color: "#4f7f68",
    summary: "The Kerala-region Paadal Petra Sthalam.",
    items: ["Thiruvanchikulam"]
  },
  {
    key: "tulu-nadu",
    label: "Tulu Nadu",
    shortLabel: "Karnataka",
    color: "#5263a3",
    summary: "The Karnataka-side shrine traditionally grouped in the wider sacred geography.",
    items: ["Gokarnam"]
  },
  {
    key: "vada-nadu",
    label: "Vada Nadu",
    shortLabel: "North India & Nepal",
    color: "#915f93",
    summary: "Northern pilgrimage destinations stretching from Andhra to the Himalayas and Nepal.",
    items: [
      "Indraneelaparvatam (Nepal)",
      "Srisailam",
      "Anekatangavadam (Gowrikund)",
      "Tirukkedaram (Kedarnath)",
      "Tirukkayilaayam (Mount Kailash)"
    ]
  }
];
